### ISSUE TITLE
PostgreSQL Tables Not Populating

### ISSUE THREAD

**Issue by s-no1ukno** [EVEIPH/EVE-SDE-Database-Builder#16]
## Problem
After completing an import to a PostgreSQL database, the tables have no rows of data in them.  The schemas are correct - the tables have the correct columns and layout, but there is no data in the tables.

![image](https://user-images.githubusercontent.com/42157737/213902312-132963e2-8ad2-41f0-a9e2-962d0d175ebb.png)

Hopefully I'm just doing something stupid and you can help me out here.

Thanks in advance!

**Comment by Zifrian** [comment]
OK, this should be fixed. Please update and try again. Bug was super embarrassing but I tested and it looks good.
