### ISSUE TITLE
sde\fsd database files not imported

### ISSUE THREAD

**Issue by wvdvegt** [EVEIPH/EVE-SDE-Database-Builder#2]
Hi

In the root of the sde\fsd folder are some additional yaml files that are not imported (for example blueprints.yaml).

**Comment by Zifrian** [comment]
Pretty sure blueprints is imported. How are you sure it's not imported? What other files?

**Comment by wvdvegt** [comment]
Think I got it, you seem to split the blueprints.yaml file into 5 tables including industryBlueprints. 

I just  exported blueprints.yaml only and got a database with 5 tables.
