### ISSUE TITLE
Import directly from zipped file

### ISSUE THREAD

**Issue by wvdvegt** [EVEIPH/EVE-SDE-Database-Builder#3]
Feature request, add an option to directly import from the sde-yyyymmdd-TRANQUILITY.zip files without having to unzip it first. Or even better also download the latest file from eve.

**Comment by Zifrian** [comment]
This isn't something I'm going to do.

**Comment by Zifrian** [comment]
With the adding of the checksum, this is apparently something I will do...and did. You can download from the newest version directly and it will unzip and build from the folder.
