### ISSUE TITLE
msSQLDB credential support incomplete

### ISSUE THREAD

**Issue by patrickebates** [EVEIPH/EVE-SDE-Database-Builder#5]
In msSQLDB.vb you have included support in `Sub New` for username and password, but then they are missing in `Function DBConnectionRef`.  Breaks when you are connecting to a SQL Server which requires those, such as Azure SQL DB.

I fixed it locally by adding additional Private Strings to the class to store the Username and Password during `Sub New` and checking for not empty later in `Function DBConnectionRef`.

**Comment by Zifrian** [comment]
Thanks, added the changes. If you could test and verify, that would be great. I no longer use sql server (and obviously didn't use passwords before!).
