### ISSUE TITLE
Could not load file or assembly system.threading..

### ISSUE THREAD

**Issue by benflanaghan** [EVEIPH/EVE-SDE-Database-Builder#9]
Hi,  I get this issue when clicking build.
just downloaded the tool and SDE data today (although did use without issue over a year ago on different computer)

![image](https://user-images.githubusercontent.com/4797988/66139604-af4c8f80-e63b-11e9-8b2b-f0d4a67e7782.png)

**Comment by Zifrian** [comment]
Ahh, I put new packages in place and it doesn't look like I update that dll in the update. I'll see what I can do about either updating or reverting some of the packages.

**Comment by Zifrian** [comment]
OK I think I got it fixed now. Open the program and run the updater. If that doesn't work for you, try downloading the binary and installing the files to try again. Let me know if it doesn't work. Thanks

**Comment by benflanaghan** [comment]
That worked, thanks a lot.   postgres load worked fine now. 👍
